type Person {
  id: ID!
  name: String!
}

type Restaurant {
  id: ID!
  name: String!
}

input PersonInput {
  userId: String!
  name: String!
  location: String!
}

input RestaurantInput {
  name: String!
  location: String!
  cuisine: String!
}

input FriendInput { 
  userId: String!
  friendId: String
}

type Query {
  getUsers: [Person]
  getFriends(userId: String!) : [Person]
}

type Mutation {
  addUser(person: PersonInput!): Person
  addRestaurant(restaurant: RestaurantInput!) : Restaurant
  addFriend(friend: FriendInput!) : String
}